<?php
    $singleData = $block->getSingleData();
?>
<div>
    <h3>Name</h3>
    <p><?php echo $singleData->getName(); ?></p>   
</div>
<div>
    <h3>Email</h3>
    <p><?php echo $singleData->getEmail(); ?></p>
</div>
<div>
    <h3>Occupation</h3>
    <p><?php echo $this->_filterProvider->getPageFilter()->filter($singleData->getOccupation()); ?></p>
</div>
<div>
	<h3>Image</h3>
	<?php if($singleData->getImage()): ?>
        <img width="400" height="300" src="<?php echo $block->getBaseUrl().'pub/media/crudexample/form/image/'.$singleData->getImage(); ?>">
    <?php else: ?>
        <p>No Image</p>
    <?php endif; ?>
</div>
<div>
    <h3>Date</h3>
    <p><?php echo $singleData->getCreatedAt(); ?></p>
</div>